language: php 

sudo: false


notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

php: 
  - 7.0 
  - 7.1 

env:
  - WP_VERSION=latest
  
script:
  - echo 'Tested' 